[colors]
[colors.primary]
background = '#00011a'
foreground = '#0008e6'

[colors.normal]
black   = "#02002e"
red     = "#FF5345"
green   = "#549e6a"
yellow  = "#c9c236"
blue    = "#021ce2"
magenta = "#D2689C"
cyan    = "#85eff5"
white   = "#ddf5f6"

[colors.bright]
black   = "#00024e"
red     = "#db9f9c"
green   = "#63b07a"
yellow  = "#E5C736"
blue    = "#acc1d4"
magenta = "#75bbb3"
cyan    = "#8CD3CB"
white   = "#9eebb3"

[colors.cursor]
text   = "#0d74f2"
cursor = "85eff5"
