[colors]
[colors.primary]
background = '#00011a'
foreground = '#0008e6'

[colors.normal]
black   = "#23372B"
red     = "#FF5345"
green   = "#549e6a"
yellow  = "#459451"
blue    = "#509475"
magenta = "#D2689C"
cyan    = "#2DD5B7"
white   = "#F6F5DD"

[colors.bright]
black   = "#53685B"
red     = "#db9f9c"
green   = "#63b07a"
yellow  = "#E5C736"
blue    = "#ACD4CF"
magenta = "#75bbb3"
cyan    = "#8CD3CB"
white   = "#9eebb3"

[colors.cursor]
text   = "#2014ff"
cursor = "#3b30ff"
